#!/usr/bin/env python3

import path
import math


print("r=20000")
print("e=1")

cadence = 30

turtle = path.Turtle(2000, 2000, 20.0)
i = 0
direction = 1
while True:
    for _ in range(0, 6):
        turtle.turn(math.pi / 55)
        turtle.forward(80 * ((i + 1)/cadence))
        if (i + direction < 0 or i + direction > cadence):
            direction = direction * -1
        i = i + direction

